// <auto-generated />
using System;
using Infrastructure.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250123201617_Corrections")]
    partial class Corrections
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("System")
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("IDGEN");

            modelBuilder.HasSequence("LOG_SEQUENCE");

            modelBuilder.HasSequence("Login_SEQ");

            modelBuilder.HasSequence("SEQ_CIRCULADOLC_ID")
                .IsCyclic();

            modelBuilder.HasSequence("SEQ_CUB_INADM")
                .IsCyclic();

            modelBuilder.HasSequence("SEQ_DOC_INAC")
                .IsCyclic();

            modelBuilder.HasSequence("SQ_Login");

            modelBuilder.Entity("Domain.Entities.Circulation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(4)
                        .IsUnicode(false)
                        .HasColumnType("character varying(4)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("character varying(25)");

                    b.HasKey("Id");

                    b.ToTable("Circulations", "System");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d2555364-565a-4b24-9104-e0d9da6585de"),
                            Abbreviation = "PE",
                            Description = "PROHIBICION ENTRADA"
                        },
                        new
                        {
                            Id = new Guid("f5f1773d-4f7b-48c5-b3ef-7f238dc28337"),
                            Abbreviation = "PS",
                            Description = "PROHIBICION SALIDA"
                        },
                        new
                        {
                            Id = new Guid("03f56eaf-ff8c-482b-bd12-9d728f972cc9"),
                            Abbreviation = "DET",
                            Description = "DETENCION"
                        },
                        new
                        {
                            Id = new Guid("c8ff6cd6-d2bc-47ff-a513-533c78ccb8ca"),
                            Abbreviation = "AE",
                            Description = "AVISO ENTRADA"
                        },
                        new
                        {
                            Id = new Guid("26dd65bf-b253-4569-ac35-d4d7a12f4513"),
                            Abbreviation = "AS",
                            Description = "AVISO SALIDA"
                        },
                        new
                        {
                            Id = new Guid("e7b1283b-082d-463b-aa1f-4be1f0ffa561"),
                            Abbreviation = "DG",
                            Description = "DROGAS"
                        },
                        new
                        {
                            Id = new Guid("d1a719b8-e836-44af-8267-10644b45010c"),
                            Abbreviation = "PE",
                            Description = "AVISO ENT/SAL"
                        },
                        new
                        {
                            Id = new Guid("5497864b-5aeb-4282-9153-7cd8f2d29d48"),
                            Abbreviation = "PE",
                            Description = "INTERES MIGRATORIO"
                        },
                        new
                        {
                            Id = new Guid("4b97beb2-4539-49cb-98a5-01db2298f1a2"),
                            Abbreviation = "PE",
                            Description = "PERDIDA DOCUMENTO"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Citizenship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Citizenships", "System");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4ee42351-6ce9-4a1e-80df-a128400a113c"),
                            Abbreviation = "AFG",
                            Description = "Afgano/a"
                        },
                        new
                        {
                            Id = new Guid("b13edbc7-7295-4c9e-839c-536f01f35a22"),
                            Abbreviation = "DEU",
                            Description = "Alemán/a"
                        },
                        new
                        {
                            Id = new Guid("d5277f54-0b72-4a73-8167-633c0bca7def"),
                            Abbreviation = "SAU",
                            Description = "Árabe Saudita"
                        },
                        new
                        {
                            Id = new Guid("93ed8147-2c88-472e-8d54-328cf25988f8"),
                            Abbreviation = "ARG",
                            Description = "Argentino/a"
                        },
                        new
                        {
                            Id = new Guid("81741e91-8d1c-493c-b6f3-49f20043b4e9"),
                            Abbreviation = "AUS",
                            Description = "Australiano/a"
                        },
                        new
                        {
                            Id = new Guid("4e80120d-c09b-4b27-bb84-196240911ee1"),
                            Abbreviation = "BEL",
                            Description = "Belga"
                        },
                        new
                        {
                            Id = new Guid("81ae5fa9-a6a8-4bb5-b58a-a335c1a2c7a1"),
                            Abbreviation = "BOL",
                            Description = "Boliviano/a"
                        },
                        new
                        {
                            Id = new Guid("fd645ab6-7f16-4c1d-83b6-f625517555cb"),
                            Abbreviation = "BRA",
                            Description = "Brasileño/a"
                        },
                        new
                        {
                            Id = new Guid("13680569-3809-4c34-a9e6-3dfb3d4b1081"),
                            Abbreviation = "KHM",
                            Description = "Camboyano/a"
                        },
                        new
                        {
                            Id = new Guid("ea649d5c-04bb-44d3-afe0-725cb188e802"),
                            Abbreviation = "CAN",
                            Description = "Canadiense"
                        },
                        new
                        {
                            Id = new Guid("02126782-533f-440b-aba4-c9ed58279ef4"),
                            Abbreviation = "CHL",
                            Description = "Chileno/a"
                        },
                        new
                        {
                            Id = new Guid("d46fda4e-7e1d-458e-b18f-45f0af5d9772"),
                            Abbreviation = "CHN",
                            Description = "Chino/a"
                        },
                        new
                        {
                            Id = new Guid("41e3b38f-111d-4c1e-822e-ebe6a0fff5a1"),
                            Abbreviation = "COL",
                            Description = "Colombiano/a"
                        },
                        new
                        {
                            Id = new Guid("2a635c18-9194-4e41-942d-a6bcac539ab3"),
                            Abbreviation = "KOR",
                            Description = "Surcoreano/a"
                        },
                        new
                        {
                            Id = new Guid("1fcc3bfe-c8b2-4468-affa-f0048181ee55"),
                            Abbreviation = "CRI",
                            Description = "Costarricense"
                        },
                        new
                        {
                            Id = new Guid("03134479-2784-415d-9e2a-f9b005809b35"),
                            Abbreviation = "CUB",
                            Description = "Cubano/a"
                        },
                        new
                        {
                            Id = new Guid("65a16a0e-4d55-43ff-918f-6caafbe08938"),
                            Abbreviation = "DNK",
                            Description = "Danés/danesa"
                        },
                        new
                        {
                            Id = new Guid("33b2df4a-2df8-407c-8d43-6df7abcfd89d"),
                            Abbreviation = "ECU",
                            Description = "Ecuatoriano/a"
                        },
                        new
                        {
                            Id = new Guid("a2f8e24b-16eb-4b90-bc49-c24c302bbd3e"),
                            Abbreviation = "EGY",
                            Description = "Egipcio/a"
                        },
                        new
                        {
                            Id = new Guid("b7e43453-7d4f-4a39-8eac-2a29ff0b093e"),
                            Abbreviation = "SLV",
                            Description = "Salvadoreño/a"
                        },
                        new
                        {
                            Id = new Guid("8800caa0-b29d-45e6-a4f3-7ca7d2e7fc94"),
                            Abbreviation = "SCO",
                            Description = "Escocés/escocesa"
                        },
                        new
                        {
                            Id = new Guid("70243148-1b69-4f2b-9e18-470f73d57759"),
                            Abbreviation = "ESP",
                            Description = "Español/a"
                        },
                        new
                        {
                            Id = new Guid("59633f2d-1ade-45a9-9ea5-7e7cc5368d3d"),
                            Abbreviation = "USA",
                            Description = "Estadounidense"
                        },
                        new
                        {
                            Id = new Guid("d46adc2c-ad5c-4a89-aa22-0829d321cb51"),
                            Abbreviation = "EST",
                            Description = "Estonio/a"
                        },
                        new
                        {
                            Id = new Guid("4368eba6-b9fc-4fe9-b12a-f4949c3cb360"),
                            Abbreviation = "ETH",
                            Description = "Etíope"
                        },
                        new
                        {
                            Id = new Guid("ebf8a598-de15-4aed-9902-e3f14d6fe3b7"),
                            Abbreviation = "PHL",
                            Description = "Filipino/a"
                        },
                        new
                        {
                            Id = new Guid("cdeaa326-2efd-47af-a20f-eeda14e64b61"),
                            Abbreviation = "FIN",
                            Description = "Finlandés/finlandesa"
                        },
                        new
                        {
                            Id = new Guid("bbab99e1-59a9-4e12-90d6-ac03fbd9f471"),
                            Abbreviation = "FRA",
                            Description = "Francés/francesa"
                        },
                        new
                        {
                            Id = new Guid("df846e75-3937-4581-9fb7-c7e5c33d7964"),
                            Abbreviation = "WAL",
                            Description = "Galés/galesa"
                        },
                        new
                        {
                            Id = new Guid("cf6518b7-39d6-4ea6-bbf6-f605df047b72"),
                            Abbreviation = "GRC",
                            Description = "Griego/a"
                        },
                        new
                        {
                            Id = new Guid("0837841b-3dcd-40f3-ba9b-cb947d1e9546"),
                            Abbreviation = "GTM",
                            Description = "Guatemalteco/a"
                        },
                        new
                        {
                            Id = new Guid("4bc9b651-ec52-4fdd-88f5-6c1e70a82fe9"),
                            Abbreviation = "HTI",
                            Description = "Haitiano/a"
                        },
                        new
                        {
                            Id = new Guid("88931b91-c983-4261-8b8f-66b42e73d403"),
                            Abbreviation = "NLD",
                            Description = "Holandés/holandesa"
                        },
                        new
                        {
                            Id = new Guid("b19ecd0d-581e-4379-8d86-5c156620f7e1"),
                            Abbreviation = "HND",
                            Description = "Hondureño/a"
                        },
                        new
                        {
                            Id = new Guid("2af2ab18-3ec2-4bc8-a806-206dfc8bf704"),
                            Abbreviation = "MYS",
                            Description = "Malayo/malaya"
                        },
                        new
                        {
                            Id = new Guid("ad432550-25bf-4149-a7c8-1c5a470717f5"),
                            Abbreviation = "MAR",
                            Description = "Marroquí/marroquí"
                        },
                        new
                        {
                            Id = new Guid("dd73a11a-6975-47ef-bfd3-571570eff689"),
                            Abbreviation = "MEX",
                            Description = "Mexicano/a"
                        },
                        new
                        {
                            Id = new Guid("b0782ecc-fd54-471d-9ff6-2897eddaaa87"),
                            Abbreviation = "NIC",
                            Description = "Nicaragüense"
                        },
                        new
                        {
                            Id = new Guid("6c32eefb-eedf-4882-aca7-282ec050cd9f"),
                            Abbreviation = "NOR",
                            Description = "Noruego/noruega"
                        },
                        new
                        {
                            Id = new Guid("84ca2900-ba5d-4360-a756-4e22e4b956e9"),
                            Abbreviation = "NZL",
                            Description = "Neozelandés/neozelandesa"
                        },
                        new
                        {
                            Id = new Guid("5fdb5db0-56f6-4ad0-b4d9-2e132b3ab075"),
                            Abbreviation = "PAN",
                            Description = "Panameño/a"
                        },
                        new
                        {
                            Id = new Guid("638cd06a-06d7-41d9-a3d8-7a4b97b5521d"),
                            Abbreviation = "PRY",
                            Description = "Paraguayo/a"
                        },
                        new
                        {
                            Id = new Guid("9715908b-1f5c-4932-a21b-d521cada27f5"),
                            Abbreviation = "PER",
                            Description = "Peruano/a"
                        },
                        new
                        {
                            Id = new Guid("08752ba4-bde3-451f-b6be-2c1bedbb4e9f"),
                            Abbreviation = "POL",
                            Description = "Polaco/polaca"
                        },
                        new
                        {
                            Id = new Guid("e6117cfc-2e8c-4fd8-8e33-42cb1a3fa325"),
                            Abbreviation = "PRT",
                            Description = "Portugués/portuguesa"
                        },
                        new
                        {
                            Id = new Guid("48dbd902-5567-4f51-9de5-d715fdf6de6e"),
                            Abbreviation = "PRI",
                            Description = "Puertorriqueño/puertorriqueña"
                        },
                        new
                        {
                            Id = new Guid("3c19aa8e-9595-4800-a806-709948befa2d"),
                            Abbreviation = "DOM",
                            Description = "Dominicano/dominicana"
                        },
                        new
                        {
                            Id = new Guid("d7bea363-7406-4004-943a-727a53ed05db"),
                            Abbreviation = "ROU",
                            Description = "Rumano/rumana"
                        },
                        new
                        {
                            Id = new Guid("7b4f0641-c5fc-4d96-b252-22be32e5ec66"),
                            Abbreviation = "RUS",
                            Description = "Ruso/rusa"
                        },
                        new
                        {
                            Id = new Guid("ddb8e711-faa1-44b2-b963-a0afcd7ed47b"),
                            Abbreviation = "SWE",
                            Description = "Sueco/sueca"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Expiration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Expirations", "System");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7572824c-b26a-4246-9cc1-a410e7c708cb"),
                            Description = "1"
                        },
                        new
                        {
                            Id = new Guid("74c77e38-bc1e-44d2-985d-4a08b2a729e5"),
                            Description = "21"
                        },
                        new
                        {
                            Id = new Guid("0f1fae44-de31-4422-ae66-b38861fcafda"),
                            Description = "90"
                        });
                });

            modelBuilder.Entity("Domain.Entities.OperationalCirculation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("BirthDate")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CirculationDate")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CirculationType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Citizenship")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset?>("Deleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ExpirationDate")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileNumber")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("character varying(36)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("character varying(12)");

                    b.Property<string>("Instruction")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LastName1")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LastName2")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Observations")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Official")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Organ")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Phone1")
                        .IsRequired()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Phone2")
                        .IsRequired()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("ReasonForCirculation")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SecondName")
                        .IsRequired()
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("character varying(12)");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "BirthDate" }, "OperationalCirculation_BirthDate");

                    b.ToTable("OperationalCirculations", "System");
                });

            modelBuilder.Entity("Domain.Entities.Organ", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Organs", "System");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7a193dbb-2a81-439b-9e3d-bd1858642930"),
                            Name = "PTI"
                        },
                        new
                        {
                            Id = new Guid("f9afd5c3-69b8-40bf-8d57-00eefcf958dc"),
                            Name = "DNA"
                        },
                        new
                        {
                            Id = new Guid("eb164951-934e-4769-aa6e-76e373684c18"),
                            Name = "DGI"
                        },
                        new
                        {
                            Id = new Guid("46328281-d46e-43a3-ac86-f666a6c5b328"),
                            Name = "DGCI"
                        },
                        new
                        {
                            Id = new Guid("23508785-117b-4525-8c07-b0326c0558ff"),
                            Name = "PNR"
                        },
                        new
                        {
                            Id = new Guid("cf9fe97a-6b31-46e5-96b2-5d2821fd2dff"),
                            Name = "DCIM"
                        },
                        new
                        {
                            Id = new Guid("804abb11-2095-4fc5-b974-a13a3bb34c32"),
                            Name = "DICO"
                        },
                        new
                        {
                            Id = new Guid("6d172f0e-295b-4b4d-a882-1be0cce75fbe"),
                            Name = "CII"
                        },
                        new
                        {
                            Id = new Guid("6990fb27-a4dd-41dc-9f20-3692b7776962"),
                            Name = "DSP"
                        },
                        new
                        {
                            Id = new Guid("9c080729-3e4f-4f13-b033-f0a104aac884"),
                            Name = "JEF-AR"
                        },
                        new
                        {
                            Id = new Guid("35314864-81d7-4bac-a495-fe9a08331bdc"),
                            Name = "JEF-MB"
                        },
                        new
                        {
                            Id = new Guid("9d67f1d7-b1e0-4122-9499-00c9dc642f17"),
                            Name = "JEF-PR"
                        },
                        new
                        {
                            Id = new Guid("a888463b-1d6c-4d6c-95f4-4a91b5559836"),
                            Name = "JEF-MA"
                        },
                        new
                        {
                            Id = new Guid("935ac142-6cf3-47fd-9ae0-4fd667991d1f"),
                            Name = "JEF-VC"
                        },
                        new
                        {
                            Id = new Guid("8a42e533-e044-4f1e-ad88-39267eb8d642"),
                            Name = "JEF-CF"
                        },
                        new
                        {
                            Id = new Guid("4f55885c-77f5-4098-b4e8-d81626c92af0"),
                            Name = "JEF-SS"
                        },
                        new
                        {
                            Id = new Guid("25777913-3813-4501-a2c0-27dbacca641f"),
                            Name = "JEF-AV"
                        },
                        new
                        {
                            Id = new Guid("1e4ce836-52b4-48e4-8d9f-f5901adb1705"),
                            Name = "JEF-CM"
                        },
                        new
                        {
                            Id = new Guid("91cbeace-b32a-4212-b4be-1aa51e9e822d"),
                            Name = "JEF-GR"
                        },
                        new
                        {
                            Id = new Guid("745766bf-8852-45c2-b4ec-ecef7d4a914b"),
                            Name = "JEF-GU"
                        },
                        new
                        {
                            Id = new Guid("ad5c5b98-73bb-4ab4-a2bd-f1f6264af835"),
                            Name = "JEF-TU"
                        },
                        new
                        {
                            Id = new Guid("97b1edd1-2453-4336-b7ff-16544428841e"),
                            Name = "JEF-ME"
                        },
                        new
                        {
                            Id = new Guid("4218b9e9-2c08-4195-a632-434673baab67"),
                            Name = "JEF-ME"
                        },
                        new
                        {
                            Id = new Guid("2e4380be-78a9-48cf-aadd-8b4ffcd7f2c4"),
                            Name = "JEF-HO"
                        },
                        new
                        {
                            Id = new Guid("b33912b7-7ae7-4eca-aef8-80af033c2529"),
                            Name = "JEF-SC"
                        },
                        new
                        {
                            Id = new Guid("526788ac-e0af-4cb9-be1c-7e993d2f98d7"),
                            Name = "PNR"
                        },
                        new
                        {
                            Id = new Guid("5913c5bd-320d-4544-96eb-cd950f46d7dd"),
                            Name = "FGR"
                        },
                        new
                        {
                            Id = new Guid("c3f9f969-5496-463c-b9bb-a35adb175657"),
                            Name = "TSP"
                        },
                        new
                        {
                            Id = new Guid("d5ed76c1-bf22-4934-b1a3-6407e07419a8"),
                            Name = "FMTAR"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
