// <auto-generated />
using System;
using Infrastructure.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250123024939_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("SISTEMA")
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("IDGEN");

            modelBuilder.HasSequence("LOG_SEQUENCE");

            modelBuilder.HasSequence("Login_SEQ");

            modelBuilder.HasSequence("SEQ_CIRCULADOLC_ID")
                .IsCyclic();

            modelBuilder.HasSequence("SEQ_CUB_INADM")
                .IsCyclic();

            modelBuilder.HasSequence("SEQ_DOC_INAC")
                .IsCyclic();

            modelBuilder.HasSequence("SQ_Login");

            modelBuilder.Entity("Domain.Entities.Circulation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(4)
                        .IsUnicode(false)
                        .HasColumnType("character varying(4)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("character varying(25)");

                    b.HasKey("Id");

                    b.ToTable("Circulations", "SISTEMA");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9ce39c36-dd03-43b4-8410-b89474e7307b"),
                            Code = "PE",
                            Description = "PROHIBICION ENTRADA"
                        },
                        new
                        {
                            Id = new Guid("f4b42694-5f71-46d9-8243-caede3cf7a50"),
                            Code = "PS",
                            Description = "PROHIBICION SALIDA"
                        },
                        new
                        {
                            Id = new Guid("8cc773f2-6ca4-47f9-8f61-04e1330154c2"),
                            Code = "DET",
                            Description = "DETENCION"
                        },
                        new
                        {
                            Id = new Guid("48e5e961-2e4c-4f79-a224-29ce34194952"),
                            Code = "AE",
                            Description = "AVISO ENTRADA"
                        },
                        new
                        {
                            Id = new Guid("5420ab8f-a599-4dfb-8d3f-607c80a43357"),
                            Code = "AS",
                            Description = "AVISO SALIDA"
                        },
                        new
                        {
                            Id = new Guid("1449e21f-a31a-49dd-8b7a-77b3d8b30aef"),
                            Code = "DG",
                            Description = "DROGAS"
                        },
                        new
                        {
                            Id = new Guid("91da3adc-3b4b-48ac-9a82-203807209c6f"),
                            Code = "PE",
                            Description = "AVISO ENT/SAL"
                        },
                        new
                        {
                            Id = new Guid("13a533c7-a9e3-42a2-b386-87657ba60871"),
                            Code = "PE",
                            Description = "INTERES MIGRATORIO"
                        },
                        new
                        {
                            Id = new Guid("32dd31bc-a1db-4182-b063-82b187c3e17e"),
                            Code = "PE",
                            Description = "PERDIDA DOCUMENTO"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Citizenship", b =>
                {
                    b.Property<decimal>("NumericCode")
                        .HasColumnType("numeric");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.HasKey("NumericCode")
                        .HasName("SYS_C001162978");

                    b.ToTable("CODPAIS", "SISTEMA");
                });

            modelBuilder.Entity("Domain.Entities.Expiration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Expirations", "SISTEMA");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6c5401c1-20e3-4500-b77b-72e328a9c454"),
                            Description = "1"
                        },
                        new
                        {
                            Id = new Guid("7bf5dfb4-7759-4c89-b835-4bc998ec1201"),
                            Description = "21"
                        },
                        new
                        {
                            Id = new Guid("3a228fee-e56a-4570-86d3-3ed1e245db32"),
                            Description = "90"
                        });
                });

            modelBuilder.Entity("Domain.Entities.OperationalCirculation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("BirthDate")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CirculationDate")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CirculationType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Citizenship")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("Deleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ExpirationDate")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileNumber")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("character varying(36)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("character varying(12)");

                    b.Property<string>("Instruction")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LastName1")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LastName2")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Observations")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Official")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Organ")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Phone1")
                        .IsRequired()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Phone2")
                        .IsRequired()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("ReasonForCirculation")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SecondName")
                        .IsRequired()
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("character varying(12)");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "BirthDate" }, "OperationalCirculation_BirthDate");

                    b.ToTable("OperationalCirculations", "SISTEMA");
                });

            modelBuilder.Entity("Domain.Entities.Organ", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Organs", "SISTEMA");

                    b.HasData(
                        new
                        {
                            Id = new Guid("46007422-aab0-4987-949c-12123032dfe0"),
                            Name = "PTI"
                        },
                        new
                        {
                            Id = new Guid("6eda93cf-d1dc-40ad-850b-c9c85c23d81e"),
                            Name = "DNA"
                        },
                        new
                        {
                            Id = new Guid("1cf6bef6-dd5a-40c4-974d-740fa90d81b5"),
                            Name = "DGI"
                        },
                        new
                        {
                            Id = new Guid("f440c502-9fea-411d-864c-f54b198ca87c"),
                            Name = "DGCI"
                        },
                        new
                        {
                            Id = new Guid("4e22905c-9efc-446e-9e25-4ba0af0f7752"),
                            Name = "PNR"
                        },
                        new
                        {
                            Id = new Guid("6930eb2c-ac02-41be-8184-25bb5fe9471e"),
                            Name = "DCIM"
                        },
                        new
                        {
                            Id = new Guid("be4da09d-6301-4abc-adfe-54f32d77e03b"),
                            Name = "DICO"
                        },
                        new
                        {
                            Id = new Guid("2c5c1707-a311-48e0-be55-45d27814059f"),
                            Name = "CII"
                        },
                        new
                        {
                            Id = new Guid("1a487931-43f3-4b1c-9f72-e05ef23ed76f"),
                            Name = "DSP"
                        },
                        new
                        {
                            Id = new Guid("3cf2a73d-b92a-4b18-b7a7-a1de942d449d"),
                            Name = "JEF-AR"
                        },
                        new
                        {
                            Id = new Guid("ffaf6f6b-a7a2-4182-bd4a-f951c6b4f16b"),
                            Name = "JEF-MB"
                        },
                        new
                        {
                            Id = new Guid("f4967882-71fe-4ee8-9461-73e51a382a31"),
                            Name = "JEF-PR"
                        },
                        new
                        {
                            Id = new Guid("3eafa6b4-c835-44e7-a7e1-8004e733442d"),
                            Name = "JEF-MA"
                        },
                        new
                        {
                            Id = new Guid("faca4fae-93f9-4dc9-9eaa-170090a0cbef"),
                            Name = "JEF-VC"
                        },
                        new
                        {
                            Id = new Guid("fbe537cd-b11d-4921-b8ce-0adc4b131adc"),
                            Name = "JEF-CF"
                        },
                        new
                        {
                            Id = new Guid("48f8fc89-c2fd-4e22-9afe-ad51fce437ea"),
                            Name = "JEF-SS"
                        },
                        new
                        {
                            Id = new Guid("5d46a206-ca3a-4a7c-9557-20d5bc4495b8"),
                            Name = "JEF-AV"
                        },
                        new
                        {
                            Id = new Guid("dfc67d51-ee8f-43d0-b9ea-c85511969460"),
                            Name = "JEF-CM"
                        },
                        new
                        {
                            Id = new Guid("f4446b55-8295-4820-823f-6ddc956361a4"),
                            Name = "JEF-GR"
                        },
                        new
                        {
                            Id = new Guid("da08c3ea-318e-4627-9765-9fbe5430d37b"),
                            Name = "JEF-GU"
                        },
                        new
                        {
                            Id = new Guid("e641df40-6510-4707-94bc-a795c81b6ac7"),
                            Name = "JEF-TU"
                        },
                        new
                        {
                            Id = new Guid("30a6a713-983d-4912-8532-aa1d46ead667"),
                            Name = "JEF-ME"
                        },
                        new
                        {
                            Id = new Guid("df6cdcd4-7533-48f6-8501-86b417b364e2"),
                            Name = "JEF-ME"
                        },
                        new
                        {
                            Id = new Guid("16a057bf-141f-4023-b5fd-a11afb5a7cc2"),
                            Name = "JEF-HO"
                        },
                        new
                        {
                            Id = new Guid("dbeacaba-8b77-4698-9eb6-039f12d15975"),
                            Name = "JEF-SC"
                        },
                        new
                        {
                            Id = new Guid("914273b0-be73-40ff-abc5-08949fd09072"),
                            Name = "PNR"
                        },
                        new
                        {
                            Id = new Guid("7dcde639-dfcd-4322-9ed4-27f022381723"),
                            Name = "FGR"
                        },
                        new
                        {
                            Id = new Guid("8f811725-ec6d-43c7-ae0c-0b05c9cf5776"),
                            Name = "TSP"
                        },
                        new
                        {
                            Id = new Guid("439c1596-5072-4d38-84cd-c2c92ade9c40"),
                            Name = "FMTAR"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
