// <auto-generated />
using System;
using Infrastructure.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250123045713_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("System")
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("IDGEN");

            modelBuilder.HasSequence("LOG_SEQUENCE");

            modelBuilder.HasSequence("Login_SEQ");

            modelBuilder.HasSequence("SEQ_CIRCULADOLC_ID")
                .IsCyclic();

            modelBuilder.HasSequence("SEQ_CUB_INADM")
                .IsCyclic();

            modelBuilder.HasSequence("SEQ_DOC_INAC")
                .IsCyclic();

            modelBuilder.HasSequence("SQ_Login");

            modelBuilder.Entity("Domain.Entities.Circulation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(4)
                        .IsUnicode(false)
                        .HasColumnType("character varying(4)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("character varying(25)");

                    b.HasKey("Id");

                    b.ToTable("Circulations", "System");

                    b.HasData(
                        new
                        {
                            Id = new Guid("719cec57-9fd0-4e3e-8bee-f41100668075"),
                            Code = "PE",
                            Description = "PROHIBICION ENTRADA"
                        },
                        new
                        {
                            Id = new Guid("716c8e89-8f87-43c6-83f2-3a536710a1ae"),
                            Code = "PS",
                            Description = "PROHIBICION SALIDA"
                        },
                        new
                        {
                            Id = new Guid("c6aa80b2-14c7-446c-90ad-1eb5619e4b99"),
                            Code = "DET",
                            Description = "DETENCION"
                        },
                        new
                        {
                            Id = new Guid("1bdd31bc-f387-411e-80ff-32a40f02e509"),
                            Code = "AE",
                            Description = "AVISO ENTRADA"
                        },
                        new
                        {
                            Id = new Guid("b95f4ea3-2e2f-478d-ae9c-41ac35bbe05b"),
                            Code = "AS",
                            Description = "AVISO SALIDA"
                        },
                        new
                        {
                            Id = new Guid("cced3da1-57bd-4223-8304-f8fbdf976052"),
                            Code = "DG",
                            Description = "DROGAS"
                        },
                        new
                        {
                            Id = new Guid("baa5a92d-0029-4f00-9689-31212ccd7020"),
                            Code = "PE",
                            Description = "AVISO ENT/SAL"
                        },
                        new
                        {
                            Id = new Guid("2d198bd0-f9dd-4f57-8729-11eeaa628ca9"),
                            Code = "PE",
                            Description = "INTERES MIGRATORIO"
                        },
                        new
                        {
                            Id = new Guid("8ccee024-1fb2-4066-b111-86c7217c4bb2"),
                            Code = "PE",
                            Description = "PERDIDA DOCUMENTO"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Citizenship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Citizenships", "System");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a33fa963-f784-4b6c-879e-6619703067da"),
                            Abbreviation = "AFG",
                            Description = "Afgano/a"
                        },
                        new
                        {
                            Id = new Guid("005c6651-e6c2-47d5-bc73-13e79d795517"),
                            Abbreviation = "DEU",
                            Description = "Alemán/a"
                        },
                        new
                        {
                            Id = new Guid("0a55d7ba-c5b3-4584-b70d-1b9dd9c5a131"),
                            Abbreviation = "SAU",
                            Description = "Árabe Saudita"
                        },
                        new
                        {
                            Id = new Guid("e99380dc-1c5f-4502-9b7d-668a699c512d"),
                            Abbreviation = "ARG",
                            Description = "Argentino/a"
                        },
                        new
                        {
                            Id = new Guid("adcdd75b-13bd-4bfd-a75d-4da5142cf09c"),
                            Abbreviation = "AUS",
                            Description = "Australiano/a"
                        },
                        new
                        {
                            Id = new Guid("62285431-878d-453c-a1a0-9480322e13b2"),
                            Abbreviation = "BEL",
                            Description = "Belga"
                        },
                        new
                        {
                            Id = new Guid("724e233e-e0b3-4d89-bb07-b7dc880acadb"),
                            Abbreviation = "BOL",
                            Description = "Boliviano/a"
                        },
                        new
                        {
                            Id = new Guid("6facfa8e-6579-4dcc-8a8b-6d30660b1af2"),
                            Abbreviation = "BRA",
                            Description = "Brasileño/a"
                        },
                        new
                        {
                            Id = new Guid("e7243554-7cc8-474e-9eb3-bfb85c9f6581"),
                            Abbreviation = "KHM",
                            Description = "Camboyano/a"
                        },
                        new
                        {
                            Id = new Guid("606740fc-a2ea-49be-884b-70cf9cabcceb"),
                            Abbreviation = "CAN",
                            Description = "Canadiense"
                        },
                        new
                        {
                            Id = new Guid("c5442f42-938d-4711-904e-a271819fd3d8"),
                            Abbreviation = "CHL",
                            Description = "Chileno/a"
                        },
                        new
                        {
                            Id = new Guid("03d61cca-1513-46db-958c-24fcf90adf27"),
                            Abbreviation = "CHN",
                            Description = "Chino/a"
                        },
                        new
                        {
                            Id = new Guid("228f3508-6b19-4385-aa0a-31e7bc072839"),
                            Abbreviation = "COL",
                            Description = "Colombiano/a"
                        },
                        new
                        {
                            Id = new Guid("e0fac894-11e0-4e98-9181-e6c270233f26"),
                            Abbreviation = "KOR",
                            Description = "Surcoreano/a"
                        },
                        new
                        {
                            Id = new Guid("a909208b-a940-4315-ba39-4c752b4affa4"),
                            Abbreviation = "CRI",
                            Description = "Costarricense"
                        },
                        new
                        {
                            Id = new Guid("9abca330-29d7-495c-b3fb-bb254502a569"),
                            Abbreviation = "CUB",
                            Description = "Cubano/a"
                        },
                        new
                        {
                            Id = new Guid("5bc7dadd-104a-43a1-9c86-1359f582fad1"),
                            Abbreviation = "DNK",
                            Description = "Danés/danesa"
                        },
                        new
                        {
                            Id = new Guid("96b03b07-e00a-4efa-915a-72008d8a05da"),
                            Abbreviation = "ECU",
                            Description = "Ecuatoriano/a"
                        },
                        new
                        {
                            Id = new Guid("a3bc6c11-d6dd-4305-bc99-fba7e00fb337"),
                            Abbreviation = "EGY",
                            Description = "Egipcio/a"
                        },
                        new
                        {
                            Id = new Guid("2d917ae9-994a-4135-aed6-b42b3abf5054"),
                            Abbreviation = "SLV",
                            Description = "Salvadoreño/a"
                        },
                        new
                        {
                            Id = new Guid("25d97325-d9b4-4879-aeff-93d91bf6e4be"),
                            Abbreviation = "SCO",
                            Description = "Escocés/escocesa"
                        },
                        new
                        {
                            Id = new Guid("e22f691f-a621-4cb5-b6cf-2006fa0b85f7"),
                            Abbreviation = "ESP",
                            Description = "Español/a"
                        },
                        new
                        {
                            Id = new Guid("2d017839-f2b1-4b8c-b823-b84b621f78b7"),
                            Abbreviation = "USA",
                            Description = "Estadounidense"
                        },
                        new
                        {
                            Id = new Guid("f9b3aa6e-1cba-43d5-8a0b-fea7944e7f28"),
                            Abbreviation = "EST",
                            Description = "Estonio/a"
                        },
                        new
                        {
                            Id = new Guid("74263ac6-4b0f-4d94-b2c5-c7c2e872530e"),
                            Abbreviation = "ETH",
                            Description = "Etíope"
                        },
                        new
                        {
                            Id = new Guid("46008117-8e96-4ab2-b536-af27dc44a94e"),
                            Abbreviation = "PHL",
                            Description = "Filipino/a"
                        },
                        new
                        {
                            Id = new Guid("3cc97ead-ce62-4f55-8cb9-2d40f01bb18e"),
                            Abbreviation = "FIN",
                            Description = "Finlandés/finlandesa"
                        },
                        new
                        {
                            Id = new Guid("bdfdd288-bfeb-458b-9a41-c8bd527b0e07"),
                            Abbreviation = "FRA",
                            Description = "Francés/francesa"
                        },
                        new
                        {
                            Id = new Guid("a29d99f8-77b4-4581-9aa9-aaf6043d1b89"),
                            Abbreviation = "WAL",
                            Description = "Galés/galesa"
                        },
                        new
                        {
                            Id = new Guid("b4619a44-c126-4196-977f-c4ad53b0cd74"),
                            Abbreviation = "GRC",
                            Description = "Griego/a"
                        },
                        new
                        {
                            Id = new Guid("74810d29-4677-434d-b1a2-972d170b283d"),
                            Abbreviation = "GTM",
                            Description = "Guatemalteco/a"
                        },
                        new
                        {
                            Id = new Guid("fe09ffb7-198c-4f43-935f-24860b90928b"),
                            Abbreviation = "HTI",
                            Description = "Haitiano/a"
                        },
                        new
                        {
                            Id = new Guid("2b1f556b-1991-4f57-815e-6d5dac62b3f3"),
                            Abbreviation = "NLD",
                            Description = "Holandés/holandesa"
                        },
                        new
                        {
                            Id = new Guid("4e27a64f-24c2-4ef4-a82b-714e589f32b9"),
                            Abbreviation = "HND",
                            Description = "Hondureño/a"
                        },
                        new
                        {
                            Id = new Guid("c19c7482-d845-43f2-b0fd-dae07ce060ed"),
                            Abbreviation = "MYS",
                            Description = "Malayo/malaya"
                        },
                        new
                        {
                            Id = new Guid("d1fb6f8c-50fb-4b68-a33e-d7b9aa259329"),
                            Abbreviation = "MAR",
                            Description = "Marroquí/marroquí"
                        },
                        new
                        {
                            Id = new Guid("ce8f6da8-679c-47e1-8ef1-8f4230349f86"),
                            Abbreviation = "MEX",
                            Description = "Mexicano/a"
                        },
                        new
                        {
                            Id = new Guid("35f2d774-7cde-4c64-a26c-fe06dd9aa2a2"),
                            Abbreviation = "NIC",
                            Description = "Nicaragüense"
                        },
                        new
                        {
                            Id = new Guid("6411072c-8a85-4ff7-a89b-b567d8d47183"),
                            Abbreviation = "NOR",
                            Description = "Noruego/noruega"
                        },
                        new
                        {
                            Id = new Guid("eb793580-a2de-4978-bf27-8ca8d1e26c72"),
                            Abbreviation = "NZL",
                            Description = "Neozelandés/neozelandesa"
                        },
                        new
                        {
                            Id = new Guid("a539eb0f-0ab9-488f-b11a-1086aafd4c3f"),
                            Abbreviation = "PAN",
                            Description = "Panameño/a"
                        },
                        new
                        {
                            Id = new Guid("ffa7fb73-02d6-4d5c-bfdb-912f3fa2f2a7"),
                            Abbreviation = "PRY",
                            Description = "Paraguayo/a"
                        },
                        new
                        {
                            Id = new Guid("fb4e044c-1099-41bb-a0ca-07cff6bc08c5"),
                            Abbreviation = "PER",
                            Description = "Peruano/a"
                        },
                        new
                        {
                            Id = new Guid("91bde1c9-98d1-493c-9a33-00b012161fe9"),
                            Abbreviation = "POL",
                            Description = "Polaco/polaca"
                        },
                        new
                        {
                            Id = new Guid("c71ef18b-f0a8-46ed-88b6-8eb4d7e25d2b"),
                            Abbreviation = "PRT",
                            Description = "Portugués/portuguesa"
                        },
                        new
                        {
                            Id = new Guid("66e03d93-7eb8-4974-a5e5-dfa91f1dc0bd"),
                            Abbreviation = "PRI",
                            Description = "Puertorriqueño/puertorriqueña"
                        },
                        new
                        {
                            Id = new Guid("81d7db5a-7947-429f-8ac9-d0c21b95d9f9"),
                            Abbreviation = "DOM",
                            Description = "Dominicano/dominicana"
                        },
                        new
                        {
                            Id = new Guid("07406b70-a8d4-42dc-9a01-45819fa3ea91"),
                            Abbreviation = "ROU",
                            Description = "Rumano/rumana"
                        },
                        new
                        {
                            Id = new Guid("fb892225-08e4-418a-a9f3-f3a0721dcc0f"),
                            Abbreviation = "RUS",
                            Description = "Ruso/rusa"
                        },
                        new
                        {
                            Id = new Guid("9aca8e69-e9cf-4be5-b92f-a89dafef30df"),
                            Abbreviation = "SWE",
                            Description = "Sueco/sueca"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Expiration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Expirations", "System");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5583fd6b-1801-4571-80df-ba9d59dff535"),
                            Description = "1"
                        },
                        new
                        {
                            Id = new Guid("1d0fa6a9-27d2-46c8-b61d-ac0da92eb3e7"),
                            Description = "21"
                        },
                        new
                        {
                            Id = new Guid("4ef0ee21-bdce-4664-acd3-96da9462c408"),
                            Description = "90"
                        });
                });

            modelBuilder.Entity("Domain.Entities.OperationalCirculation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("BirthDate")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CirculationDate")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CirculationType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Citizenship")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("Deleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ExpirationDate")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileNumber")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("character varying(36)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("character varying(12)");

                    b.Property<string>("Instruction")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LastName1")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LastName2")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Observations")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Official")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Organ")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Phone1")
                        .IsRequired()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Phone2")
                        .IsRequired()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("ReasonForCirculation")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SecondName")
                        .IsRequired()
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("character varying(12)");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "BirthDate" }, "OperationalCirculation_BirthDate");

                    b.ToTable("OperationalCirculations", "System");
                });

            modelBuilder.Entity("Domain.Entities.Organ", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Organs", "System");

                    b.HasData(
                        new
                        {
                            Id = new Guid("37261ea7-8218-450d-8dcf-770ab9728b81"),
                            Name = "PTI"
                        },
                        new
                        {
                            Id = new Guid("a15bbb25-af61-4f9a-b9f3-8e74f5dadcf0"),
                            Name = "DNA"
                        },
                        new
                        {
                            Id = new Guid("2db4ce92-243a-42a1-8092-8cc4e525ce7e"),
                            Name = "DGI"
                        },
                        new
                        {
                            Id = new Guid("42ea6d67-1393-4faa-9458-1b17b1a1c383"),
                            Name = "DGCI"
                        },
                        new
                        {
                            Id = new Guid("43a8fb74-1f67-4800-909e-b28b987fdd55"),
                            Name = "PNR"
                        },
                        new
                        {
                            Id = new Guid("87fafff0-05db-47b7-8f7e-7b1c82f7aef9"),
                            Name = "DCIM"
                        },
                        new
                        {
                            Id = new Guid("47acb459-5499-47d7-b349-b32663ce012e"),
                            Name = "DICO"
                        },
                        new
                        {
                            Id = new Guid("accd0205-b24d-4abd-9dd4-bf5baacec6e7"),
                            Name = "CII"
                        },
                        new
                        {
                            Id = new Guid("7524f6e0-2b28-4ea0-9a5d-bbc7bccc998a"),
                            Name = "DSP"
                        },
                        new
                        {
                            Id = new Guid("468c93ef-aa8f-4d89-93a0-8c8d9e631ca2"),
                            Name = "JEF-AR"
                        },
                        new
                        {
                            Id = new Guid("4c8614e7-97ec-413c-b4b8-6ad96d1f0b72"),
                            Name = "JEF-MB"
                        },
                        new
                        {
                            Id = new Guid("14dc5d56-88c1-4948-9abd-3b46d6b34be3"),
                            Name = "JEF-PR"
                        },
                        new
                        {
                            Id = new Guid("0534eb14-3bb6-4446-a2ae-f239df13387a"),
                            Name = "JEF-MA"
                        },
                        new
                        {
                            Id = new Guid("5e766101-dde9-4978-b27a-cf84a5e10444"),
                            Name = "JEF-VC"
                        },
                        new
                        {
                            Id = new Guid("b1e32c7d-2a1c-4164-8d93-f77b12bc30ab"),
                            Name = "JEF-CF"
                        },
                        new
                        {
                            Id = new Guid("29f6e1fe-fabe-472f-8a85-0930d1f35a9d"),
                            Name = "JEF-SS"
                        },
                        new
                        {
                            Id = new Guid("436932a9-9c6e-4f0b-9392-e90111c99e13"),
                            Name = "JEF-AV"
                        },
                        new
                        {
                            Id = new Guid("61c898d1-195b-45f5-9b89-0fcbd45ddc8d"),
                            Name = "JEF-CM"
                        },
                        new
                        {
                            Id = new Guid("1cca1b5e-0872-41f1-9ae8-0af2bf66422b"),
                            Name = "JEF-GR"
                        },
                        new
                        {
                            Id = new Guid("82cb9c16-a1a3-4173-94b7-6ac3cfcfa1e4"),
                            Name = "JEF-GU"
                        },
                        new
                        {
                            Id = new Guid("4c9220fd-72a6-4f55-983b-14af6460a48f"),
                            Name = "JEF-TU"
                        },
                        new
                        {
                            Id = new Guid("3deecb6a-ac6a-4c94-b4f3-1749ff261d89"),
                            Name = "JEF-ME"
                        },
                        new
                        {
                            Id = new Guid("99f374e6-372e-454a-9085-e0be8356c0d7"),
                            Name = "JEF-ME"
                        },
                        new
                        {
                            Id = new Guid("37bbeecf-97b9-40b6-b3f5-526a18f281a0"),
                            Name = "JEF-HO"
                        },
                        new
                        {
                            Id = new Guid("86fbeaf5-beb4-4267-91b2-e7d038596468"),
                            Name = "JEF-SC"
                        },
                        new
                        {
                            Id = new Guid("89258072-fb9b-49be-a442-19ed6860af25"),
                            Name = "PNR"
                        },
                        new
                        {
                            Id = new Guid("adc0dea4-a88e-4974-817f-85d7947d3c7b"),
                            Name = "FGR"
                        },
                        new
                        {
                            Id = new Guid("c7bf384c-904d-4b2f-a2c0-4e8a7f956625"),
                            Name = "TSP"
                        },
                        new
                        {
                            Id = new Guid("c0190a05-1fab-47c2-925c-49a81d27ea9d"),
                            Name = "FMTAR"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
