// <auto-generated />
using System;
using Infrastructure.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("System")
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("IDGEN");

            modelBuilder.HasSequence("LOG_SEQUENCE");

            modelBuilder.HasSequence("Login_SEQ");

            modelBuilder.HasSequence("SEQ_CIRCULADOLC_ID")
                .IsCyclic();

            modelBuilder.HasSequence("SEQ_CUB_INADM")
                .IsCyclic();

            modelBuilder.HasSequence("SEQ_DOC_INAC")
                .IsCyclic();

            modelBuilder.HasSequence("SQ_Login");

            modelBuilder.Entity("Domain.Entities.Circulation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CirculationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CirculationTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CitizenshipId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("Deleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ExpirationId")
                        .HasColumnType("uuid");

                    b.Property<string>("FileNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Instruction")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName1")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LastName2")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Observations")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Official")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("OrganId")
                        .HasColumnType("uuid");

                    b.Property<string>("Phone1")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("Phone2")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("ReasonForCirculation")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("SecondName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("BirthDate");

                    b.HasIndex("CirculationTypeId");

                    b.HasIndex("CitizenshipId");

                    b.HasIndex("ExpirationId");

                    b.HasIndex("FirstName");

                    b.HasIndex("LastName1");

                    b.HasIndex("LastName2");

                    b.HasIndex("OrganId");

                    b.ToTable("Circulations", "System");
                });

            modelBuilder.Entity("Domain.Entities.CirculationType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.HasKey("Id");

                    b.ToTable("CirculationTypes", "System");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9cb20464-174f-490c-950a-f0a433033d12"),
                            Abbreviation = "PE",
                            Description = "PROHIBICION ENTRADA"
                        },
                        new
                        {
                            Id = new Guid("5ab8562c-2de5-4c96-a673-20a7b32fefbe"),
                            Abbreviation = "PS",
                            Description = "PROHIBICION SALIDA"
                        },
                        new
                        {
                            Id = new Guid("79489eae-62fa-4278-879b-e441a26bc572"),
                            Abbreviation = "DET",
                            Description = "DETENCION"
                        },
                        new
                        {
                            Id = new Guid("c6f5c452-734b-4603-a9b1-10171b2d50d5"),
                            Abbreviation = "AE",
                            Description = "AVISO ENTRADA"
                        },
                        new
                        {
                            Id = new Guid("bca08ff3-f585-44b5-addc-d27399bf6dbd"),
                            Abbreviation = "AS",
                            Description = "AVISO SALIDA"
                        },
                        new
                        {
                            Id = new Guid("1f610708-d1ae-4b2b-a7f4-46bacff268bd"),
                            Abbreviation = "DG",
                            Description = "DROGAS"
                        },
                        new
                        {
                            Id = new Guid("5b200913-2ef1-404a-9bb5-d10de63eb10f"),
                            Abbreviation = "PE",
                            Description = "AVISO ENT/SAL"
                        },
                        new
                        {
                            Id = new Guid("109f0cd1-28a1-4cfe-aec9-db26c030f737"),
                            Abbreviation = "PE",
                            Description = "INTERES MIGRATORIO"
                        },
                        new
                        {
                            Id = new Guid("acbc1ddb-e8ee-452e-b8e2-57e0c3631557"),
                            Abbreviation = "PE",
                            Description = "PERDIDA DOCUMENTO"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Citizenship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Citizenships", "System");

                    b.HasData(
                        new
                        {
                            Id = new Guid("760c93a1-19fa-401e-90a3-4e6a3540a9e9"),
                            Abbreviation = "AFG",
                            Description = "Afgano/a"
                        },
                        new
                        {
                            Id = new Guid("a45b93d3-78b7-487d-ba06-4d40f0a65a71"),
                            Abbreviation = "DEU",
                            Description = "Alemán/a"
                        },
                        new
                        {
                            Id = new Guid("e4f82a02-0c1f-4800-9bf9-d18f89dbf6a0"),
                            Abbreviation = "SAU",
                            Description = "Árabe Saudita"
                        },
                        new
                        {
                            Id = new Guid("ea69f972-6187-4276-9783-44037cd9121b"),
                            Abbreviation = "ARG",
                            Description = "Argentino/a"
                        },
                        new
                        {
                            Id = new Guid("4c5766ce-000b-4b4c-a4e5-f2745230d927"),
                            Abbreviation = "AUS",
                            Description = "Australiano/a"
                        },
                        new
                        {
                            Id = new Guid("95311a20-3593-4e82-b982-77dde7971141"),
                            Abbreviation = "BEL",
                            Description = "Belga"
                        },
                        new
                        {
                            Id = new Guid("6b28addb-20a9-4f2e-a8f8-647dfd2ee300"),
                            Abbreviation = "BOL",
                            Description = "Boliviano/a"
                        },
                        new
                        {
                            Id = new Guid("cfe868f6-b86c-4615-b945-0c625f7cb579"),
                            Abbreviation = "BRA",
                            Description = "Brasileño/a"
                        },
                        new
                        {
                            Id = new Guid("21ef8495-604c-4b0d-89a0-47246d80b633"),
                            Abbreviation = "KHM",
                            Description = "Camboyano/a"
                        },
                        new
                        {
                            Id = new Guid("d7053f1d-fb86-4981-a9c4-5bff3a4a819b"),
                            Abbreviation = "CAN",
                            Description = "Canadiense"
                        },
                        new
                        {
                            Id = new Guid("eb817c9d-6abe-4953-996d-7d4d8530d8f7"),
                            Abbreviation = "CHL",
                            Description = "Chileno/a"
                        },
                        new
                        {
                            Id = new Guid("e0532d85-4842-44b1-9e3a-9df292a85cbb"),
                            Abbreviation = "CHN",
                            Description = "Chino/a"
                        },
                        new
                        {
                            Id = new Guid("1fd12829-4bb7-4889-8542-6176bc6a974c"),
                            Abbreviation = "COL",
                            Description = "Colombiano/a"
                        },
                        new
                        {
                            Id = new Guid("28e193e6-c06c-4ba1-9d0f-06c8d960889e"),
                            Abbreviation = "KOR",
                            Description = "Surcoreano/a"
                        },
                        new
                        {
                            Id = new Guid("edb33ef0-0ebc-40c2-b8a6-533e859b049a"),
                            Abbreviation = "CRI",
                            Description = "Costarricense"
                        },
                        new
                        {
                            Id = new Guid("c6f686c2-8fac-4c26-8ed4-4216ebe17baa"),
                            Abbreviation = "CUB",
                            Description = "Cubano/a"
                        },
                        new
                        {
                            Id = new Guid("05d09da6-5fac-4cc0-8358-4732e73bc73c"),
                            Abbreviation = "DNK",
                            Description = "Danés/danesa"
                        },
                        new
                        {
                            Id = new Guid("7de38f35-fb73-4db2-afe4-b0ed3a2b5c0e"),
                            Abbreviation = "ECU",
                            Description = "Ecuatoriano/a"
                        },
                        new
                        {
                            Id = new Guid("9f98fb4f-4ce9-4a23-b166-11b37a4006eb"),
                            Abbreviation = "EGY",
                            Description = "Egipcio/a"
                        },
                        new
                        {
                            Id = new Guid("46cf1d6d-3df5-41f8-866a-2a21891ab0d8"),
                            Abbreviation = "SLV",
                            Description = "Salvadoreño/a"
                        },
                        new
                        {
                            Id = new Guid("339277e2-38aa-467f-9601-17b331cfd90f"),
                            Abbreviation = "SCO",
                            Description = "Escocés/escocesa"
                        },
                        new
                        {
                            Id = new Guid("2473cf73-303e-4177-b057-f363f95cfef0"),
                            Abbreviation = "ESP",
                            Description = "Español/a"
                        },
                        new
                        {
                            Id = new Guid("f9b77cae-de8d-4c95-87f1-1a4eead0340f"),
                            Abbreviation = "USA",
                            Description = "Estadounidense"
                        },
                        new
                        {
                            Id = new Guid("c4a531f8-7fb2-4d2d-83d1-069d8e110ff5"),
                            Abbreviation = "EST",
                            Description = "Estonio/a"
                        },
                        new
                        {
                            Id = new Guid("e491b15b-4f30-40b7-967c-1e54225195d4"),
                            Abbreviation = "ETH",
                            Description = "Etíope"
                        },
                        new
                        {
                            Id = new Guid("f756e3bd-3847-4071-9071-9ecda63ccc6d"),
                            Abbreviation = "PHL",
                            Description = "Filipino/a"
                        },
                        new
                        {
                            Id = new Guid("c1780c40-cc95-4f0a-a423-1ef4a038def9"),
                            Abbreviation = "FIN",
                            Description = "Finlandés/finlandesa"
                        },
                        new
                        {
                            Id = new Guid("3130862f-fe23-4c39-8290-af08dcea08a1"),
                            Abbreviation = "FRA",
                            Description = "Francés/francesa"
                        },
                        new
                        {
                            Id = new Guid("8923e927-8195-4858-8453-d9dd29831c7b"),
                            Abbreviation = "WAL",
                            Description = "Galés/galesa"
                        },
                        new
                        {
                            Id = new Guid("aa2fc645-89c3-4244-8dea-91a9fcd4acd5"),
                            Abbreviation = "GRC",
                            Description = "Griego/a"
                        },
                        new
                        {
                            Id = new Guid("a4dcad00-69a8-4fe7-8189-0a847ddff42f"),
                            Abbreviation = "GTM",
                            Description = "Guatemalteco/a"
                        },
                        new
                        {
                            Id = new Guid("b8901589-f599-4325-9cfc-5e1b69395f26"),
                            Abbreviation = "HTI",
                            Description = "Haitiano/a"
                        },
                        new
                        {
                            Id = new Guid("3830c231-4fe2-4dd9-8abd-8a4b220bb765"),
                            Abbreviation = "NLD",
                            Description = "Holandés/holandesa"
                        },
                        new
                        {
                            Id = new Guid("42972d1d-eecc-45ad-816e-107c08a66a8d"),
                            Abbreviation = "HND",
                            Description = "Hondureño/a"
                        },
                        new
                        {
                            Id = new Guid("4c2aa7a2-ac94-4501-a36b-d17ca349ea8f"),
                            Abbreviation = "MYS",
                            Description = "Malayo/malaya"
                        },
                        new
                        {
                            Id = new Guid("09cfb083-9edb-453d-90ff-87c0aa4f76fb"),
                            Abbreviation = "MAR",
                            Description = "Marroquí/marroquí"
                        },
                        new
                        {
                            Id = new Guid("3c7e8c7b-420e-42f3-a234-afb2e8444ca5"),
                            Abbreviation = "MEX",
                            Description = "Mexicano/a"
                        },
                        new
                        {
                            Id = new Guid("2304e933-78f2-4006-81dc-978eb33ed616"),
                            Abbreviation = "NIC",
                            Description = "Nicaragüense"
                        },
                        new
                        {
                            Id = new Guid("5fcc300d-f86d-41c7-9c20-8e96750fe50e"),
                            Abbreviation = "NOR",
                            Description = "Noruego/noruega"
                        },
                        new
                        {
                            Id = new Guid("70bf3d60-f937-4fb2-a9f4-fdca76432b20"),
                            Abbreviation = "NZL",
                            Description = "Neozelandés/neozelandesa"
                        },
                        new
                        {
                            Id = new Guid("65b12e34-6f79-47e3-95af-178d8485d77b"),
                            Abbreviation = "PAN",
                            Description = "Panameño/a"
                        },
                        new
                        {
                            Id = new Guid("81233b8e-5e5f-4796-aef0-8981f446c023"),
                            Abbreviation = "PRY",
                            Description = "Paraguayo/a"
                        },
                        new
                        {
                            Id = new Guid("057656cd-a89e-4ee4-937b-40b5b1d4264c"),
                            Abbreviation = "PER",
                            Description = "Peruano/a"
                        },
                        new
                        {
                            Id = new Guid("e9bc1ac5-8f40-4a98-855a-3982d8adbb61"),
                            Abbreviation = "POL",
                            Description = "Polaco/polaca"
                        },
                        new
                        {
                            Id = new Guid("bc515ba8-c7ab-4a64-915a-0085240d2b9c"),
                            Abbreviation = "PRT",
                            Description = "Portugués/portuguesa"
                        },
                        new
                        {
                            Id = new Guid("e82e2453-881d-4175-bbbd-50a9fc0eb264"),
                            Abbreviation = "PRI",
                            Description = "Puertorriqueño/puertorriqueña"
                        },
                        new
                        {
                            Id = new Guid("7b7d05f1-fc8e-4380-a0b0-81c753ad8e17"),
                            Abbreviation = "DOM",
                            Description = "Dominicano/dominicana"
                        },
                        new
                        {
                            Id = new Guid("deea262c-cde1-4e43-b0ca-8f5d97dbe3cf"),
                            Abbreviation = "ROU",
                            Description = "Rumano/rumana"
                        },
                        new
                        {
                            Id = new Guid("302ddb87-874b-45a0-9350-3898a8aac678"),
                            Abbreviation = "RUS",
                            Description = "Ruso/rusa"
                        },
                        new
                        {
                            Id = new Guid("ab6e050f-02fc-4226-9ef0-886b6533dc6b"),
                            Abbreviation = "SWE",
                            Description = "Sueco/sueca"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Expiration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.HasKey("Id");

                    b.ToTable("Expirations", "System");

                    b.HasData(
                        new
                        {
                            Id = new Guid("96dc2d4d-6fdc-4af1-ba61-1b3eb9714311"),
                            Description = "1"
                        },
                        new
                        {
                            Id = new Guid("74ba8f43-9618-48eb-a5d0-94b7ccdbbea8"),
                            Description = "21"
                        },
                        new
                        {
                            Id = new Guid("11ab35ff-cb80-493a-bfc6-591404f064cc"),
                            Description = "90"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Organ", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.ToTable("Organs", "System");

                    b.HasData(
                        new
                        {
                            Id = new Guid("db515b03-98d4-4b24-b2ef-74e6c4c618f0"),
                            Name = "PTI"
                        },
                        new
                        {
                            Id = new Guid("3df3411c-5ac0-4de9-9826-86182ce2ec8a"),
                            Name = "DNA"
                        },
                        new
                        {
                            Id = new Guid("1f609388-dbe5-48a4-9f9c-cfbbe5adeeed"),
                            Name = "DGI"
                        },
                        new
                        {
                            Id = new Guid("85a4e9dd-a6a4-46e4-a4d9-8efdfa1e6de2"),
                            Name = "DGCI"
                        },
                        new
                        {
                            Id = new Guid("9e487360-d593-44f0-ac47-79123819e20e"),
                            Name = "PNR"
                        },
                        new
                        {
                            Id = new Guid("bfe91010-bf36-4739-a5f8-4ad1d365d884"),
                            Name = "DCIM"
                        },
                        new
                        {
                            Id = new Guid("705bb7db-3405-4a4d-9090-5a13956fdf60"),
                            Name = "DICO"
                        },
                        new
                        {
                            Id = new Guid("e51ebdd7-e30c-48ff-bdb2-d4921f890b11"),
                            Name = "CII"
                        },
                        new
                        {
                            Id = new Guid("642f674f-1989-4698-871d-481709f54ae9"),
                            Name = "DSP"
                        },
                        new
                        {
                            Id = new Guid("26094401-cee2-4fb1-9f04-3462995fef7e"),
                            Name = "JEF-AR"
                        },
                        new
                        {
                            Id = new Guid("6d4e0d7d-1bdb-41ee-b6b3-498df19d1f47"),
                            Name = "JEF-MB"
                        },
                        new
                        {
                            Id = new Guid("3185e85e-12a0-4275-822e-b7e4a2e9b9aa"),
                            Name = "JEF-PR"
                        },
                        new
                        {
                            Id = new Guid("44b7e3af-0bce-420e-8b97-cccb1e1dbb75"),
                            Name = "JEF-MA"
                        },
                        new
                        {
                            Id = new Guid("363b4f69-d24c-4fdd-9b0b-4fc10266c85c"),
                            Name = "JEF-VC"
                        },
                        new
                        {
                            Id = new Guid("d9258bd5-a2f0-4288-9998-0ab5bfb89cc4"),
                            Name = "JEF-CF"
                        },
                        new
                        {
                            Id = new Guid("487c22e9-6e73-43d2-8561-bbb4ba3b2be5"),
                            Name = "JEF-SS"
                        },
                        new
                        {
                            Id = new Guid("0d830f46-06e6-4f8f-943b-f7308a00005f"),
                            Name = "JEF-AV"
                        },
                        new
                        {
                            Id = new Guid("03fb1cf0-1f09-474f-8b27-b12af623d207"),
                            Name = "JEF-CM"
                        },
                        new
                        {
                            Id = new Guid("8d31738d-2a1c-4bdd-9e3d-fd4081155091"),
                            Name = "JEF-GR"
                        },
                        new
                        {
                            Id = new Guid("4f69a27d-41d8-4cc5-bd21-cc2c9a31e62a"),
                            Name = "JEF-GU"
                        },
                        new
                        {
                            Id = new Guid("15fb9d84-3d73-470d-a6fb-d3d2e843cfbe"),
                            Name = "JEF-TU"
                        },
                        new
                        {
                            Id = new Guid("1ecdfc3e-8514-4449-a905-93ec51c3de6b"),
                            Name = "JEF-ME"
                        },
                        new
                        {
                            Id = new Guid("b91fe38f-5d2f-42de-a134-95854b0e5817"),
                            Name = "JEF-ME"
                        },
                        new
                        {
                            Id = new Guid("963729bc-a83e-4558-b5fb-c98635833e6f"),
                            Name = "JEF-HO"
                        },
                        new
                        {
                            Id = new Guid("45a08086-1dc9-4060-b872-21d8ee3db1e1"),
                            Name = "JEF-SC"
                        },
                        new
                        {
                            Id = new Guid("d722bebd-092c-45f0-9a6c-64540ab5ff8d"),
                            Name = "PNR"
                        },
                        new
                        {
                            Id = new Guid("6e89b8de-0de8-4e5f-8450-427ac74a53b2"),
                            Name = "FGR"
                        },
                        new
                        {
                            Id = new Guid("a9c35fdc-205a-4941-9860-5face7f17d60"),
                            Name = "TSP"
                        },
                        new
                        {
                            Id = new Guid("a2f5bd59-3ad8-4f31-8987-e85d2f930d47"),
                            Name = "FMTAR"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Circulation", b =>
                {
                    b.HasOne("Domain.Entities.CirculationType", "CirculationType")
                        .WithMany("Circulations")
                        .HasForeignKey("CirculationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Citizenship", "Citizenship")
                        .WithMany("Circulations")
                        .HasForeignKey("CitizenshipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Expiration", "Expiration")
                        .WithMany("Circulations")
                        .HasForeignKey("ExpirationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Organ", "Organ")
                        .WithMany("Circulations")
                        .HasForeignKey("OrganId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CirculationType");

                    b.Navigation("Citizenship");

                    b.Navigation("Expiration");

                    b.Navigation("Organ");
                });

            modelBuilder.Entity("Domain.Entities.CirculationType", b =>
                {
                    b.Navigation("Circulations");
                });

            modelBuilder.Entity("Domain.Entities.Citizenship", b =>
                {
                    b.Navigation("Circulations");
                });

            modelBuilder.Entity("Domain.Entities.Expiration", b =>
                {
                    b.Navigation("Circulations");
                });

            modelBuilder.Entity("Domain.Entities.Organ", b =>
                {
                    b.Navigation("Circulations");
                });
#pragma warning restore 612, 618
        }
    }
}
